name: Hello World Action
on: [workflow_dispatch] # Allows you to run it manually from the Actions tab

jobs:
  say-hello:
    runs-on: self-hosted
    steps:
      - name: Greet the user
        run: echo "Hello World!"
