name: Install httpd
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: who am i 
        run: whoami

      - name: List all environment variables 
        run: env

      - name: check export command output
        run: export

      - name: what is github workspace
        run: echo "workspace location ${{github.workspace}}"

      - name: Install httpd 
        run: sudo yum install httpd -y 
