name: Node.js CI
on: [workflow_dispatch]
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: Linux
    steps:
      - uses: actions/checkout@v4 # Clones your code onto the runner
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Speeds up subsequent runs
      - run: npm install
      - run: npm test
